# Generated by Django 5.0.1 on 2024-01-27 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0002_peluquero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_elegido', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('completada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber_app.cliente')),
                ('peluquero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber_app.peluquero')),
            ],
        ),
    ]
